version: 2.1

orbs:
  gcp-secret-sync: vjpandian/gcp-secret-sync@dev:alpha
  orb-tools: circleci/orb-tools@11.5
  gcp-cli: circleci/gcp-cli@3.2.2

parameters:
  secret_name:
    type: string
    default: "google-cloud-gar-secrets"

filters: &filters
  tags:
    only: /.*/

jobs:
  gcp-secret-sync-test:
    docker:
      - image: cimg/python:3.13.2
    steps:
      - checkout
      - gcp-secret-sync/sync-secrets:
          secret_name: << pipeline.parameters.secret_name >>


workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - gcp-secret-sync-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: vjpandian/gcp-secret-sync
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - gcp-secret-sync-test
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

