version: 2.1

orbs:
  gcp-secret-sync: vjpandian/gcp-secret-sync@dev:alpha
  orb-tools: circleci/orb-tools@11.5
  gcp-cli: circleci/gcp-cli@3.2.2

parameters:
  secret_name:
    type: string
    default: "google-cloud-gar-secrets"
  gcp-project-number:
    type: string
    default: "676320558565"
  gcp-project-id:    
    default: "dev-vijay-pandian"
    type: string
  oidc-wip-pool:
    type: string
    default: "vijay-cci-cloud-pool"
  oidc-wip-provider:
    type: string
    default: "vijay-cci-cloud-pool-provider-id"
  gcp-sa:
    type: string
    default: "vijay-cci-cloud-gcp-sa@dev-vijay-pandian.iam.gserviceaccount.com"

commands:              
  setup-oidc:
    steps:
      - gcp-cli/setup:
           use_oidc: true
           google_project_number: GOOGLE_PROJECT_ID
           google_project_id: GOOGLE_PROJECT_ID
           workload_identity_pool_id: OIDC_WIP_ID
           workload_identity_pool_provider_id: OIDC_WIP_PROVIDER_ID
           service_account_email: OIDC_SERVICE_ACCOUNT_EMAIL


filters: &filters
  tags:
    only: /.*/

jobs:
  gcp-secret-sync-test:
    docker:
      - image: cimg/python:3.13.2
    resource_class: small
    environment: &common_env
      GOOGLE_PROJECT_NUMBER: << pipeline.parameters.gcp-project-number >>
      GOOGLE_PROJECT_ID: << pipeline.parameters.gcp-project-number >>
      OIDC_WIP_PROVIDER_ID: << pipeline.parameters.oidc-wip-provider >>
      OIDC_WIP_ID: << pipeline.parameters.oidc-wip-pool >>
      OIDC_SERVICE_ACCOUNT_EMAIL: << pipeline.parameters.gcp-sa >>
      SECRET_NAME: << pipeline.parameters.secret_name >>
    steps:
      - checkout
      - setup-oidc
      - run:
          name: Fetch and Sync secrets
          command: bash src/scripts/sync-secrets.sh



workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - gcp-secret-sync-test:
          filters: *filters
          context: org-global
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: vjpandian/gcp-secret-sync
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - gcp-secret-sync-test
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

