---
description: >
  This is a sample executor using Docker and Node for running applications

docker:
  - image: 'cimg/node:<<parameters.tag>>'

parameters:
  tag:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
